name: publish faucet docker image

on:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, ci-runner]    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: "matterlabs/faucet:latest"
          file: Dockerfile
          no-cache: true
